[package]
name = "internal_ci"
version = "0.1.0"
authors = ["Jasper Visser <jasperav@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdrs_ci = { path = "../cdrs_ci" }
dotenv = "0.15"