# This file is generated, don't edit

name: tests-cassandra

on: push

env:
  CARGO_TERM_COLOR: always
  TEST_CDRS_DB_KEYSPACE_KEY: test_keyspace_for_testing

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
       # crates
      - name: clean cdrs_orm_util
        run: cargo +nightly clean --package cdrs_orm_util
      - name: build cdrs_orm_util
        run: cargo +nightly build --package cdrs_orm_util --jobs=1
      - name: fmt cdrs_orm_util
        run: cargo +nightly fmt --package cdrs_orm_util
      - name: fix cdrs_orm_util
        run: cargo +nightly fix --package cdrs_orm_util --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_orm_util
        run: cargo +nightly test --package cdrs_orm_util --verbose -- --test-threads=1
      - name: clippy cdrs_orm_util
        run: cargo +nightly clippy --package cdrs_orm_util --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_orm_util
        run: cargo +nightly clean --package cdrs_orm_util
      - name: build cdrs_orm_util
        run: cargo +nightly build --package cdrs_orm_util --jobs=1
      - name: clippy cdrs_orm_util
        run: cargo +nightly clippy --package cdrs_orm_util -- -D warnings

      - name: clean cdrs_con
        run: cargo +nightly clean --package cdrs_con
      - name: build cdrs_con
        run: cargo +nightly build --package cdrs_con --jobs=1
      - name: fmt cdrs_con
        run: cargo +nightly fmt --package cdrs_con
      - name: fix cdrs_con
        run: cargo +nightly fix --package cdrs_con --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_con
        run: cargo +nightly test --package cdrs_con --verbose -- --test-threads=1
