# This file is generated, don't edit

name: tests-scylladb

on: push

env:
  CARGO_TERM_COLOR: always
  TEST_CDRS_DB_KEYSPACE_KEY: test_keyspace_for_testing

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.50.0-nightly
          components: rustfmt, clippy
       # crates
      - name: Install cargo expand
        run: cargo install cargo-expand
      - name: clean test_derived_equals
        run: cargo +nightly clean --package test_derived_equals
      - name: build test_derived_equals
        run: cargo +nightly build --package test_derived_equals --jobs=1
      - name: fmt test_derived_equals
        run: cargo +nightly fmt --package test_derived_equals
      - name: fix test_derived_equals
        run: cargo +nightly fix --package test_derived_equals --all-features --allow-dirty --allow-staged --jobs=1
      - name: test test_derived_equals
        run: cargo +nightly test --package test_derived_equals --verbose -- --test-threads=1
      - name: clippy test_derived_equals
        run: cargo +nightly clippy --package test_derived_equals --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean test_derived_equals
        run: cargo +nightly clean --package test_derived_equals
      - name: build test_derived_equals
        run: cargo +nightly build --package test_derived_equals --jobs=1
      - name: clippy test_derived_equals
        run: cargo +nightly clippy --package test_derived_equals -- -D warnings

