# This file is generated, don't edit

name: tests-scylladb

on: push

env:
  CARGO_TERM_COLOR: always
  TEST_CDRS_DB_KEYSPACE_KEY: test_keyspace_for_testing
  CAMEL_CASE_TO_DB_SNAKE_CASE: 1
  RUSTFLAGS: -Aclippy::from_over_into

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
       # crates
      - name: clean cdrs_orm_util
        run: cargo +nightly clean --package cdrs_orm_util
      - name: build cdrs_orm_util
        run: cargo +nightly build --package cdrs_orm_util --jobs=1
      - name: fmt cdrs_orm_util
        run: cargo +nightly fmt --package cdrs_orm_util
      - name: fix cdrs_orm_util
        run: cargo +nightly fix --package cdrs_orm_util --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_orm_util
        run: cargo +nightly test --package cdrs_orm_util --verbose -- --test-threads=1
      - name: clippy cdrs_orm_util
        run: cargo +nightly clippy --package cdrs_orm_util --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_orm_util
        run: cargo +nightly clean --package cdrs_orm_util
      - name: build cdrs_orm_util
        run: cargo +nightly build --package cdrs_orm_util --jobs=1
      - name: clippy cdrs_orm_util
        run: cargo +nightly clippy --package cdrs_orm_util -- -D warnings

      - name: clean cdrs_con
        run: cargo +nightly clean --package cdrs_con
      - name: build cdrs_con
        run: cargo +nightly build --package cdrs_con --jobs=1
      - name: fmt cdrs_con
        run: cargo +nightly fmt --package cdrs_con
      - name: fix cdrs_con
        run: cargo +nightly fix --package cdrs_con --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_con
        run: cargo +nightly test --package cdrs_con --verbose -- --test-threads=1
      - name: clippy cdrs_con
        run: cargo +nightly clippy --package cdrs_con --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_con
        run: cargo +nightly clean --package cdrs_con
      - name: build cdrs_con
        run: cargo +nightly build --package cdrs_con --jobs=1
      - name: clippy cdrs_con
        run: cargo +nightly clippy --package cdrs_con -- -D warnings

      - name: clean cdrs_db_mirror
        run: cargo +nightly clean --package cdrs_db_mirror
      - name: build cdrs_db_mirror
        run: cargo +nightly build --package cdrs_db_mirror --jobs=1
      - name: fmt cdrs_db_mirror
        run: cargo +nightly fmt --package cdrs_db_mirror
      - name: fix cdrs_db_mirror
        run: cargo +nightly fix --package cdrs_db_mirror --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_db_mirror
        run: cargo +nightly test --package cdrs_db_mirror --verbose -- --test-threads=1
      - name: clippy cdrs_db_mirror
        run: cargo +nightly clippy --package cdrs_db_mirror --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_db_mirror
        run: cargo +nightly clean --package cdrs_db_mirror
      - name: build cdrs_db_mirror
        run: cargo +nightly build --package cdrs_db_mirror --jobs=1
      - name: clippy cdrs_db_mirror
        run: cargo +nightly clippy --package cdrs_db_mirror -- -D warnings

      - name: clean cdrs_query_writer
        run: cargo +nightly clean --package cdrs_query_writer
      - name: build cdrs_query_writer
        run: cargo +nightly build --package cdrs_query_writer --jobs=1
      - name: fmt cdrs_query_writer
        run: cargo +nightly fmt --package cdrs_query_writer
      - name: fix cdrs_query_writer
        run: cargo +nightly fix --package cdrs_query_writer --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_query_writer
        run: cargo +nightly test --package cdrs_query_writer --verbose -- --test-threads=1
      - name: clippy cdrs_query_writer
        run: cargo +nightly clippy --package cdrs_query_writer --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_query_writer
        run: cargo +nightly clean --package cdrs_query_writer
      - name: build cdrs_query_writer
        run: cargo +nightly build --package cdrs_query_writer --jobs=1
      - name: clippy cdrs_query_writer
        run: cargo +nightly clippy --package cdrs_query_writer -- -D warnings

      - name: clean cdrs_to_rust
        run: cargo +nightly clean --package cdrs_to_rust
      - name: build cdrs_to_rust
        run: cargo +nightly build --package cdrs_to_rust --jobs=1
      - name: fmt cdrs_to_rust
        run: cargo +nightly fmt --package cdrs_to_rust
      - name: fix cdrs_to_rust
        run: cargo +nightly fix --package cdrs_to_rust --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_to_rust
        run: cargo +nightly test --package cdrs_to_rust --verbose -- --test-threads=1
      - name: clippy cdrs_to_rust
        run: cargo +nightly clippy --package cdrs_to_rust --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_to_rust
        run: cargo +nightly clean --package cdrs_to_rust
      - name: build cdrs_to_rust
        run: cargo +nightly build --package cdrs_to_rust --jobs=1
      - name: clippy cdrs_to_rust
        run: cargo +nightly clippy --package cdrs_to_rust -- -D warnings

      - name: clean cdrs_query
        run: cargo +nightly clean --package cdrs_query
      - name: build cdrs_query
        run: cargo +nightly build --package cdrs_query --jobs=1
      - name: fmt cdrs_query
        run: cargo +nightly fmt --package cdrs_query
      - name: fix cdrs_query
        run: cargo +nightly fix --package cdrs_query --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_query
        run: cargo +nightly test --package cdrs_query --verbose -- --test-threads=1
      - name: clippy cdrs_query
        run: cargo +nightly clippy --package cdrs_query --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_query
        run: cargo +nightly clean --package cdrs_query
      - name: build cdrs_query
        run: cargo +nightly build --package cdrs_query --jobs=1
      - name: clippy cdrs_query
        run: cargo +nightly clippy --package cdrs_query -- -D warnings

      - name: clean cdrs_query_example
        run: cargo +nightly clean --package cdrs_query_example
      - name: build cdrs_query_example
        run: cargo +nightly build --package cdrs_query_example --jobs=1
      - name: fmt cdrs_query_example
        run: cargo +nightly fmt --package cdrs_query_example
      - name: fix cdrs_query_example
        run: cargo +nightly fix --package cdrs_query_example --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_query_example
        run: cargo +nightly test --package cdrs_query_example --verbose -- --test-threads=1
      - name: clippy cdrs_query_example
        run: cargo +nightly clippy --package cdrs_query_example --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_query_example
        run: cargo +nightly clean --package cdrs_query_example
      - name: build cdrs_query_example
        run: cargo +nightly build --package cdrs_query_example --jobs=1
      - name: clippy cdrs_query_example
        run: cargo +nightly clippy --package cdrs_query_example -- -D warnings

      - name: clean cdrs_query_example_proc_macro
        run: cargo +nightly clean --package cdrs_query_example_proc_macro
      - name: build cdrs_query_example_proc_macro
        run: cargo +nightly build --package cdrs_query_example_proc_macro --jobs=1
      - name: fmt cdrs_query_example_proc_macro
        run: cargo +nightly fmt --package cdrs_query_example_proc_macro
      - name: fix cdrs_query_example_proc_macro
        run: cargo +nightly fix --package cdrs_query_example_proc_macro --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_query_example_proc_macro
        run: cargo +nightly test --package cdrs_query_example_proc_macro --verbose -- --test-threads=1
      - name: clippy cdrs_query_example_proc_macro
        run: cargo +nightly clippy --package cdrs_query_example_proc_macro --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_query_example_proc_macro
        run: cargo +nightly clean --package cdrs_query_example_proc_macro
      - name: build cdrs_query_example_proc_macro
        run: cargo +nightly build --package cdrs_query_example_proc_macro --jobs=1
      - name: clippy cdrs_query_example_proc_macro
        run: cargo +nightly clippy --package cdrs_query_example_proc_macro -- -D warnings

      - name: clean cdrs_query_simple
        run: cargo +nightly clean --package cdrs_query_simple
      - name: build cdrs_query_simple
        run: cargo +nightly build --package cdrs_query_simple --jobs=1
      - name: fmt cdrs_query_simple
        run: cargo +nightly fmt --package cdrs_query_simple
      - name: fix cdrs_query_simple
        run: cargo +nightly fix --package cdrs_query_simple --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_query_simple
        run: cargo +nightly test --package cdrs_query_simple --verbose -- --test-threads=1
      - name: clippy cdrs_query_simple
        run: cargo +nightly clippy --package cdrs_query_simple --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_query_simple
        run: cargo +nightly clean --package cdrs_query_simple
      - name: build cdrs_query_simple
        run: cargo +nightly build --package cdrs_query_simple --jobs=1
      - name: clippy cdrs_query_simple
        run: cargo +nightly clippy --package cdrs_query_simple -- -D warnings

      - name: clean cdrs_query_simple_example
        run: cargo +nightly clean --package cdrs_query_simple_example
      - name: build cdrs_query_simple_example
        run: cargo +nightly build --package cdrs_query_simple_example --jobs=1
      - name: fmt cdrs_query_simple_example
        run: cargo +nightly fmt --package cdrs_query_simple_example
      - name: fix cdrs_query_simple_example
        run: cargo +nightly fix --package cdrs_query_simple_example --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_query_simple_example
        run: cargo +nightly test --package cdrs_query_simple_example --verbose -- --test-threads=1
      - name: clippy cdrs_query_simple_example
        run: cargo +nightly clippy --package cdrs_query_simple_example --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_query_simple_example
        run: cargo +nightly clean --package cdrs_query_simple_example
      - name: build cdrs_query_simple_example
        run: cargo +nightly build --package cdrs_query_simple_example --jobs=1
      - name: clippy cdrs_query_simple_example
        run: cargo +nightly clippy --package cdrs_query_simple_example -- -D warnings

      - name: clean example_db_mirror
        run: cargo +nightly clean --package example_db_mirror
      - name: build example_db_mirror
        run: cargo +nightly build --package example_db_mirror --jobs=1
      - name: fmt example_db_mirror
        run: cargo +nightly fmt --package example_db_mirror
      - name: fix example_db_mirror
        run: cargo +nightly fix --package example_db_mirror --all-features --allow-dirty --allow-staged --jobs=1
      - name: test example_db_mirror
        run: cargo +nightly test --package example_db_mirror --verbose -- --test-threads=1
      - name: clippy example_db_mirror
        run: cargo +nightly clippy --package example_db_mirror --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean example_db_mirror
        run: cargo +nightly clean --package example_db_mirror
      - name: build example_db_mirror
        run: cargo +nightly build --package example_db_mirror --jobs=1
      - name: clippy example_db_mirror
        run: cargo +nightly clippy --package example_db_mirror -- -D warnings

      - name: clean example_impl_writer
        run: cargo +nightly clean --package example_impl_writer
      - name: build example_impl_writer
        run: cargo +nightly build --package example_impl_writer --jobs=1
      - name: fmt example_impl_writer
        run: cargo +nightly fmt --package example_impl_writer
      - name: fix example_impl_writer
        run: cargo +nightly fix --package example_impl_writer --all-features --allow-dirty --allow-staged --jobs=1
      - name: test example_impl_writer
        run: cargo +nightly test --package example_impl_writer --verbose -- --test-threads=1
      - name: clippy example_impl_writer
        run: cargo +nightly clippy --package example_impl_writer --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean example_impl_writer
        run: cargo +nightly clean --package example_impl_writer
      - name: build example_impl_writer
        run: cargo +nightly build --package example_impl_writer --jobs=1
      - name: clippy example_impl_writer
        run: cargo +nightly clippy --package example_impl_writer -- -D warnings

      - name: clean custom_derive
        run: cargo +nightly clean --package custom_derive
      - name: build custom_derive
        run: cargo +nightly build --package custom_derive --jobs=1
      - name: fmt custom_derive
        run: cargo +nightly fmt --package custom_derive
      - name: fix custom_derive
        run: cargo +nightly fix --package custom_derive --all-features --allow-dirty --allow-staged --jobs=1
      - name: test custom_derive
        run: cargo +nightly test --package custom_derive --verbose -- --test-threads=1
      - name: clippy custom_derive
        run: cargo +nightly clippy --package custom_derive --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean custom_derive
        run: cargo +nightly clean --package custom_derive
      - name: build custom_derive
        run: cargo +nightly build --package custom_derive --jobs=1
      - name: clippy custom_derive
        run: cargo +nightly clippy --package custom_derive -- -D warnings

      - name: clean cdrs_ci
        run: cargo +nightly clean --package cdrs_ci
      - name: build cdrs_ci
        run: cargo +nightly build --package cdrs_ci --jobs=1
      - name: fmt cdrs_ci
        run: cargo +nightly fmt --package cdrs_ci
      - name: fix cdrs_ci
        run: cargo +nightly fix --package cdrs_ci --all-features --allow-dirty --allow-staged --jobs=1
      - name: test cdrs_ci
        run: cargo +nightly test --package cdrs_ci --verbose -- --test-threads=1
      - name: clippy cdrs_ci
        run: cargo +nightly clippy --package cdrs_ci --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean cdrs_ci
        run: cargo +nightly clean --package cdrs_ci
      - name: build cdrs_ci
        run: cargo +nightly build --package cdrs_ci --jobs=1
      - name: clippy cdrs_ci
        run: cargo +nightly clippy --package cdrs_ci -- -D warnings

      - name: fmt internal_ci
        run: cargo +nightly fmt --package internal_ci
      - name: fix internal_ci
        run: cargo +nightly fix --package internal_ci --all-features --allow-dirty --allow-staged --jobs=1
      - name: test internal_ci
        run: cargo +nightly test --package internal_ci --verbose -- --test-threads=1
      - name: clippy internal_ci
        run: cargo +nightly clippy --package internal_ci --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clippy internal_ci
        run: cargo +nightly clippy --package internal_ci -- -D warnings

      - name: Install cargo expand
        run: cargo install cargo-expand
      - name: clean test_derived_equals
        run: cargo +nightly clean --package test_derived_equals
      - name: build test_derived_equals
        run: cargo +nightly build --package test_derived_equals --jobs=1
      - name: fmt test_derived_equals
        run: cargo +nightly fmt --package test_derived_equals
      - name: fix test_derived_equals
        run: cargo +nightly fix --package test_derived_equals --all-features --allow-dirty --allow-staged --jobs=1
      - name: test test_derived_equals
        run: cargo +nightly test --package test_derived_equals --verbose -- --test-threads=1
      - name: clippy test_derived_equals
        run: cargo +nightly clippy --package test_derived_equals --fix -Z unstable-options --allow-dirty --allow-staged
      - name: clean test_derived_equals
        run: cargo +nightly clean --package test_derived_equals
      - name: build test_derived_equals
        run: cargo +nightly build --package test_derived_equals --jobs=1
      - name: clippy test_derived_equals
        run: cargo +nightly clippy --package test_derived_equals -- -D warnings

