# This file is generated, don't edit

name: tests-scylladb

on: push

env:
  CARGO_TERM_COLOR: always
  TEST_CDRS_DB_KEYSPACE_KEY: test_keyspace_for_testing
  CAMEL_CASE_TO_DB_SNAKE_CASE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
       # crates
      - name: clean cdrs_orm_util
        run: cargo clean --package cdrs_orm_util
      - name: build cdrs_orm_util
        run: cargo build --package cdrs_orm_util --jobs=1
      - name: test cdrs_orm_util
        run: cargo test --package cdrs_orm_util --verbose -- --test-threads=1
      - name: clean cdrs_orm_util
        run: cargo clean --package cdrs_orm_util
      - name: build cdrs_orm_util
        run: cargo build --package cdrs_orm_util --jobs=1
      - name: clippy cdrs_orm_util
        run: cargo clippy --package cdrs_orm_util -- -D warnings

      - name: clean cdrs_con
        run: cargo clean --package cdrs_con
      - name: build cdrs_con
        run: cargo build --package cdrs_con --jobs=1
      - name: test cdrs_con
        run: cargo test --package cdrs_con --verbose -- --test-threads=1
      - name: clean cdrs_con
        run: cargo clean --package cdrs_con
      - name: build cdrs_con
        run: cargo build --package cdrs_con --jobs=1
      - name: clippy cdrs_con
        run: cargo clippy --package cdrs_con -- -D warnings

      - name: clean cdrs_db_mirror
        run: cargo clean --package cdrs_db_mirror
      - name: build cdrs_db_mirror
        run: cargo build --package cdrs_db_mirror --jobs=1
      - name: test cdrs_db_mirror
        run: cargo test --package cdrs_db_mirror --verbose -- --test-threads=1
      - name: clean cdrs_db_mirror
        run: cargo clean --package cdrs_db_mirror
      - name: build cdrs_db_mirror
        run: cargo build --package cdrs_db_mirror --jobs=1
      - name: clippy cdrs_db_mirror
        run: cargo clippy --package cdrs_db_mirror -- -D warnings

      - name: clean cdrs_query_writer
        run: cargo clean --package cdrs_query_writer
      - name: build cdrs_query_writer
        run: cargo build --package cdrs_query_writer --jobs=1
      - name: test cdrs_query_writer
        run: cargo test --package cdrs_query_writer --verbose -- --test-threads=1
      - name: clean cdrs_query_writer
        run: cargo clean --package cdrs_query_writer
      - name: build cdrs_query_writer
        run: cargo build --package cdrs_query_writer --jobs=1
      - name: clippy cdrs_query_writer
        run: cargo clippy --package cdrs_query_writer -- -D warnings

      - name: clean cdrs_to_rust
        run: cargo clean --package cdrs_to_rust
      - name: build cdrs_to_rust
        run: cargo build --package cdrs_to_rust --jobs=1
      - name: test cdrs_to_rust
        run: cargo test --package cdrs_to_rust --verbose -- --test-threads=1
      - name: clean cdrs_to_rust
        run: cargo clean --package cdrs_to_rust
      - name: build cdrs_to_rust
        run: cargo build --package cdrs_to_rust --jobs=1
      - name: clippy cdrs_to_rust
        run: cargo clippy --package cdrs_to_rust -- -D warnings

      - name: clean cdrs_query
        run: cargo clean --package cdrs_query
      - name: build cdrs_query
        run: cargo build --package cdrs_query --jobs=1
      - name: test cdrs_query
        run: cargo test --package cdrs_query --verbose -- --test-threads=1
      - name: clean cdrs_query
        run: cargo clean --package cdrs_query
      - name: build cdrs_query
        run: cargo build --package cdrs_query --jobs=1
      - name: clippy cdrs_query
        run: cargo clippy --package cdrs_query -- -D warnings

      - name: clean cdrs_query_example
        run: cargo clean --package cdrs_query_example
      - name: build cdrs_query_example
        run: cargo build --package cdrs_query_example --jobs=1
      - name: test cdrs_query_example
        run: cargo test --package cdrs_query_example --verbose -- --test-threads=1
      - name: clean cdrs_query_example
        run: cargo clean --package cdrs_query_example
      - name: build cdrs_query_example
        run: cargo build --package cdrs_query_example --jobs=1
      - name: clippy cdrs_query_example
        run: cargo clippy --package cdrs_query_example -- -D warnings

      - name: clean cdrs_query_example_proc_macro
        run: cargo clean --package cdrs_query_example_proc_macro
      - name: build cdrs_query_example_proc_macro
        run: cargo build --package cdrs_query_example_proc_macro --jobs=1
      - name: test cdrs_query_example_proc_macro
        run: cargo test --package cdrs_query_example_proc_macro --verbose -- --test-threads=1
      - name: clean cdrs_query_example_proc_macro
        run: cargo clean --package cdrs_query_example_proc_macro
      - name: build cdrs_query_example_proc_macro
        run: cargo build --package cdrs_query_example_proc_macro --jobs=1
      - name: clippy cdrs_query_example_proc_macro
        run: cargo clippy --package cdrs_query_example_proc_macro -- -D warnings

      - name: clean cdrs_query_simple
        run: cargo clean --package cdrs_query_simple
      - name: build cdrs_query_simple
        run: cargo build --package cdrs_query_simple --jobs=1
      - name: test cdrs_query_simple
        run: cargo test --package cdrs_query_simple --verbose -- --test-threads=1
      - name: clean cdrs_query_simple
        run: cargo clean --package cdrs_query_simple
      - name: build cdrs_query_simple
        run: cargo build --package cdrs_query_simple --jobs=1
      - name: clippy cdrs_query_simple
        run: cargo clippy --package cdrs_query_simple -- -D warnings

      - name: clean cdrs_query_simple_example
        run: cargo clean --package cdrs_query_simple_example
      - name: build cdrs_query_simple_example
        run: cargo build --package cdrs_query_simple_example --jobs=1
      - name: test cdrs_query_simple_example
        run: cargo test --package cdrs_query_simple_example --verbose -- --test-threads=1
      - name: clean cdrs_query_simple_example
        run: cargo clean --package cdrs_query_simple_example
      - name: build cdrs_query_simple_example
        run: cargo build --package cdrs_query_simple_example --jobs=1
      - name: clippy cdrs_query_simple_example
        run: cargo clippy --package cdrs_query_simple_example -- -D warnings

      - name: clean example_db_mirror
        run: cargo clean --package example_db_mirror
      - name: build example_db_mirror
        run: cargo build --package example_db_mirror --jobs=1
      - name: test example_db_mirror
        run: cargo test --package example_db_mirror --verbose -- --test-threads=1
      - name: clean example_db_mirror
        run: cargo clean --package example_db_mirror
      - name: build example_db_mirror
        run: cargo build --package example_db_mirror --jobs=1
      - name: clippy example_db_mirror
        run: cargo clippy --package example_db_mirror -- -D warnings

      - name: clean example_impl_writer
        run: cargo clean --package example_impl_writer
      - name: build example_impl_writer
        run: cargo build --package example_impl_writer --jobs=1
      - name: test example_impl_writer
        run: cargo test --package example_impl_writer --verbose -- --test-threads=1
      - name: clean example_impl_writer
        run: cargo clean --package example_impl_writer
      - name: build example_impl_writer
        run: cargo build --package example_impl_writer --jobs=1
      - name: clippy example_impl_writer
        run: cargo clippy --package example_impl_writer -- -D warnings

      - name: clean custom_derive
        run: cargo clean --package custom_derive
      - name: build custom_derive
        run: cargo build --package custom_derive --jobs=1
      - name: test custom_derive
        run: cargo test --package custom_derive --verbose -- --test-threads=1
      - name: clean custom_derive
        run: cargo clean --package custom_derive
      - name: build custom_derive
        run: cargo build --package custom_derive --jobs=1
      - name: clippy custom_derive
        run: cargo clippy --package custom_derive -- -D warnings

      - name: clean cdrs_ci
        run: cargo clean --package cdrs_ci
      - name: build cdrs_ci
        run: cargo build --package cdrs_ci --jobs=1
      - name: test cdrs_ci
        run: cargo test --package cdrs_ci --verbose -- --test-threads=1
      - name: clean cdrs_ci
        run: cargo clean --package cdrs_ci
      - name: build cdrs_ci
        run: cargo build --package cdrs_ci --jobs=1
      - name: clippy cdrs_ci
        run: cargo clippy --package cdrs_ci -- -D warnings

      - name: test internal_ci
        run: cargo test --package internal_ci --verbose -- --test-threads=1
      - name: clippy internal_ci
        run: cargo clippy --package internal_ci -- -D warnings

      - name: Install cargo expand
        run: cargo install cargo-expand

